DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS myList CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE rooms (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id),
  address VARCHAR(255) NOT NULL,
  price VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  taken BOOLEAN DEFAULT 'N',
  posted_date VARCHAR(255) NOT NULL,
  photos TEXT []
);

CREATE TABLE myList (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  room_id INTEGER REFERENCES rooms(id)
)